### ISSUE TITLE
Add dialog that prompts users to "Rate the App"

### ISSUE THREAD

**Issue by anguyen2DOE** [anguyen2DOE/Feed-Your-Mind-Mobile-App#5]
Apps usually prompt the user to Rate the App. The choices that users can take are as follows:

1) Rate Now : This options opens up the page where the user can rate the app - users can rate once per version update. This dialog should prompt to users again after every version update.
2) Later : This closes the dialog and will return to prompt again to the user at a later time, date, and/or session.
3) Never : This closes the dialog and does not return until the next version update.

**Comment by ajamil** [comment]
Has been added in version 1.0.8
